-- <query promotion_effectiveness>
-- <description>Measures promotion ROI: revenue generated by promoted sales vs non-promoted sales, and revenue uplift vs promotion cost. Join PROMOTION using SS_PROMO_SK. NULL SS_PROMO_SK means no promotion.</description>
-- <query>
WITH promoted_sales AS (
    SELECT
        p.P_PROMO_NAME,
        p.P_PURPOSE,
        p.P_COST                                AS promo_marketing_cost,
        COUNT(DISTINCT ss.SS_TICKET_NUMBER)     AS promoted_transactions,
        SUM(ss.SS_EXT_SALES_PRICE)              AS promoted_revenue,
        SUM(ss.SS_COUPON_AMT)                   AS total_coupon_discount,
        SUM(ss.SS_NET_PROFIT)                   AS promoted_profit
    FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES ss
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.PROMOTION p
        ON ss.SS_PROMO_SK = p.P_PROMO_SK
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.DATE_DIM d
        ON ss.SS_SOLD_DATE_SK = d.D_DATE_SK
    WHERE d.D_YEAR = 2001
    GROUP BY p.P_PROMO_NAME, p.P_PURPOSE, p.P_COST
)
SELECT
    P_PROMO_NAME                                            AS promotion,
    P_PURPOSE                                               AS purpose,
    promoted_transactions,
    ROUND(promoted_revenue, 2)                              AS promoted_revenue,
    ROUND(total_coupon_discount, 2)                         AS total_coupon_discount,
    ROUND(promoted_profit, 2)                               AS promoted_profit,
    ROUND(promo_marketing_cost, 2)                          AS marketing_cost,
    ROUND(promoted_revenue / NULLIF(promo_marketing_cost, 0), 2) AS revenue_per_marketing_dollar,
    ROUND((promoted_revenue - promo_marketing_cost - total_coupon_discount) / NULLIF(promo_marketing_cost, 0) * 100, 2) AS roi_pct
FROM promoted_sales
ORDER BY promoted_revenue DESC
LIMIT 25;
-- </query>
